CREATE TABLE "words"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "key_work"    varchar(255),
    "description" text,
    "voice_id"    int,
    "spelling"    varchar(255),
    "topic_id"    int,
    "class_id"    int,
    "sec"         int,
    "is_hidden"   bool,
    "reg_time"    timestamp default now(),
    "reg_user"    int,
    "update_time" timestamp default now(),
    "update_user" int
);

CREATE TABLE "topics"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "topic_name"  varchar(500),
    "class_id"    int,
    "thumbnail"   varchar(500),
    "sec"         int,
    "is_hidden"   bool,
    "reg_time"    timestamp default now(),
    "reg_user"    int,
    "update_time" timestamp default now(),
    "update_user" int
);

CREATE TABLE "classes"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "class_name"  int,
    "sec"         int,
    "thumbnail"   varchar(500),
    "reg_time"    timestamp default now(),
    "reg_user"    int,
    "update_time" timestamp default now(),
    "update_user" int
);

CREATE TABLE "users"
(
    "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"       varchar(255),
    "first_name"     varchar(500),
    "last_name"      varchar(500),
    "role_id"        int,
    "birthday"       timestamp default now(),
    "address"        varchar(500),
    "phone"          varchar(11),
    "mail"           varchar(255),
    "school_name"    varchar(255),
    "school_city"    varchar(255),
    "school_ward"    varchar(255),
    "school_address" varchar(255),
    "locked_flag"    bool,
    "del_flag"       bool,
    "login_provider" varchar(100),
    "reg_time"       timestamp default now(),
    "reg_user"       int,
    "update_time"    timestamp default now(),
    "update_user"    int
);

CREATE TABLE "roles"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name"   int,
    "reg_time"    timestamp default now(),
    "reg_user"    int,
    "update_time" timestamp default now(),
    "update_user" int
);

CREATE TABLE "voices"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "key"         varchar(255),
    "path"        varchar(255),
    "reg_time"    timestamp default now(),
    "reg_user"    int,
    "update_time" timestamp default now(),
    "update_user" int
);

CREATE TABLE "my_favorite_topics"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "topic_id"    int,
    "user_id"     int,
    "reg_time"    timestamp default now(),
    "reg_user"    int,
    "update_time" timestamp default now(),
    "update_user" int
);

CREATE TABLE "my_notebooks"
(
    "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"       int,
    "notebook_name" varchar(255),
    "thumbnail"     varchar(255),
    "reg_time"      timestamp default now(),
    "reg_user"      int,
    "update_time"   timestamp default now(),
    "update_user"   int
);

CREATE TABLE "my_notebook_words"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "notebook_id" int,
    "word_id"     int,
    "sec"         int,
    "reg_time"    timestamp default now(),
    "reg_user"    int,
    "update_time" timestamp default now(),
    "update_user" int
);

CREATE TABLE "count_view_topic"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "topic_id"    int,
    "view_count"  int,
    "reg_time"    timestamp default now(),
    "reg_user"    int,
    "update_time" timestamp default now(),
    "update_user" int
);